//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long chatid { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string gener { get; set; }
    }
}
